### ISSUE TITLE
RGB integration into OpenRGB

### ISSUE THREAD

**Issue by CalcProgrammer1** [flukejones/rog-core#1]
I'm the developer of an RGB control application called OpenRGB.  My goal is to support as many RGB devices as possible in one unified API and program.  I would be interested in adding support for the laptops you're researching.  My app currently does not provide a daemon, but my goal is to have one daemon that handles hardware communication with all RGB devices eventually (once I get the network API figured out).

If you're interested, check out my project: https://gitlab.com/CalcProgrammer1/OpenRGB

If you want to add some of the devices I support to your project, I have documented a bunch of protocol information on my project wiki.

Thanks,
Adam

**Comment by flukejones** [comment]
Hey, I did find your project earlier, looks like a mamoth project. I can't contribute unfortunately - C or C++ is not a language I know much of anymore and I won't be picking it back up in the future since Rust is enabling me to do a lot more in safer ways with better guarantees.

This project also has a slightly different goal where it targets only ASUS ROG laptops. You are welcome to use the information I provide in various comments/data of course.
